version: "2"

services:
  unifi:
    image: jacobalberty/unifi
    container_name: docker-unifi
    restart: always
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "/your/host/folder/unifi:/unifi"
      - "/your/host/folder/var/lib/unifi:/var/lib/unifi"
      - "/your/host/folder/var/log/unifi:/var/log/unifi"
      - "/your/host/folder/var/run/unifi:/var/run/unifi"
      - "/your/host/folder/usr/lib/unifi/work:/usr/lib/unifi/work"
    ports:
      - "8843:8843"
      - "8080:8080"
      - "8081:8081"
      - "3478:3478/udp"
    environment:
      - VIRTUAL_HOST=unifi.your.domain
      - VIRTUAL_NETWORK=webproxy
      - VIRTUAL_PORT=8443
      - VIRTUAL_PROTO=https
      - LETSENCRYPT_HOST=unifi.your.domain
      - LETSENCRYPT_EMAIL=your@email.adress
    networks:
      - webproxy

networks:
  webproxy:
    external:
      name: webproxy
      